from rich.layout import Layout
from rich.panel import Panel
from rich.table import Table
from rich.text import Text

from app.reporting.cost_summary import create_cost_table


def create_layout(scan_data):
    layout = Layout(name="root")

    # Main Layout
    layout.split_column(
        Layout(name="header", size=3),
        Layout(name="body"),
        Layout(name="footer", size=3),
    )

    layout["body"].split_row(
        Layout(name="left", ratio=3),
        Layout(name="right", ratio=2),
    )

    layout["left"].split_column(
        Layout(name="summary"),
        Layout(name="cost"),
    )

    # ---------------- HEADER ----------------
    layout["header"].update(
        Panel(
            Text(
                "Cloud Infrastructure Auditor & Cost Optimizer",
                justify="center",
                style="bold cyan",
            )
        )
    )

    # ---------------- SUMMARY TABLE ----------------
    table = Table(
    show_header=True,
    header_style="bold cyan",
    )

    table.add_column("Metric")
    table.add_column("Value", justify="center")

    table.add_row("Total Resources", str(scan_data["total_resources"]))
    table.add_row("Passed", str(scan_data["passed"]))
    table.add_row("Warnings", str(scan_data["warnings"]))
    table.add_row("Critical", str(scan_data["critical"]))

    layout["summary"].update(
        Panel(
            table,
            title="Scan Summary",
            border_style="cyan",
        )
    )

    # ---------------- COST SUMMARY ----------------
    cost_data = {
        "EC2": 120,
        "S3": 35,
        "RDS": 60,
        "Lambda": 12,
    }

    cost_table = create_cost_table(cost_data)

    layout["cost"].update(
        Panel(
            cost_table,
            title="Estimated Monthly Cost",
            border_style="green",
        )
    )

    # ---------------- RECOMMENDATIONS ----------------
    recommendations = ""

    for item in scan_data["recommendations"]:
        recommendations += f"• {item}\n"

    layout["right"].update(
        Panel(
            recommendations,
            title="Recommendations",
            border_style="yellow",
        )
    )

    # ---------------- FOOTER ----------------
    layout["footer"].update(
        Panel(
            "Generated by Reporting Module",
            style="green",
        )
    )

    return layout