from rich.console import Console
from rich.layout import Layout
from rich.panel import Panel
from rich.text import Text
from rich.table import Table

console = Console()


def create_layout(scan_data):
    layout = Layout(name="root")

    # Main Layout
    layout.split_column(
        Layout(name="header", size=3),
        Layout(name="body"),
        Layout(name="footer", size=3),
    )

    # Body Layout
    layout["body"].split_row(
        Layout(name="left", ratio=2),
        Layout(name="right", ratio=1),
    )

    # Header
    layout["header"].update(
        Panel(
            Text(
                "Cloud Infrastructure Auditor & Cost Optimizer",
                justify="center",
                style="bold cyan",
            )
        )
    )

    # Summary Table
    table = Table(show_header=True, header_style="bold cyan")
    table.add_column("Metric", style="white")
    table.add_column("Value", justify="center", style="green")

    table.add_row("Total Resources", str(scan_data["total_resources"]))
    table.add_row("Passed", str(scan_data["passed"]))
    table.add_row("Warnings", str(scan_data["warnings"]))
    table.add_row("Critical", str(scan_data["critical"]))

    layout["left"].update(
        Panel(
            table,
            title="Scan Summary",
            border_style="cyan",
        )
    )

    # Recommendations
    recommendations = ""

    for item in scan_data["recommendations"]:
        recommendations += f"• {item}\n"

    layout["right"].update(
        Panel(
            recommendations,
            title="Recommendations",
            border_style="yellow",
        )
    )

    # Footer
    layout["footer"].update(
        Panel(
            "Generated by Reporting Module",
            style="green",
        )
    )

    return layout