from rich.console import Console
from rich.layout import Layout
from rich.panel import Panel
from rich.text import Text

console = Console()


def create_layout():
    layout = Layout(name="root")

    layout.split_column(
        Layout(name="header", size=3),
        Layout(name="body"),
        Layout(name="footer", size=3),
    )

    layout["body"].split_row(
        Layout(name="left"),
        Layout(name="right")
    )

    layout["header"].update(
        Panel(
            Text(
                "Cloud Infrastructure Auditor & Cost Optimizer",
                justify="center",
                style="bold cyan"
            )
        )
    )

    layout["left"].update(
        Panel(
            "Scan Summary\n\nWaiting for data...",
            title="Summary"
        )
    )

    layout["right"].update(
        Panel(
            "Recommendations\n\nWaiting for data...",
            title="Recommendations"
        )
    )

    layout["footer"].update(
        Panel(
            "Generated by Reporting Module",
            style="green"
        )
    )

    return layout